name: Main

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: er28-0652/setup-ghidra@master
        with:
          version: "9.2.4"

      - name: Build with Gradle
        working-directory: ./GhidraJupyterKotlin
        run: gradle buildExtension

      - name: Debug github.ref
        run: echo ${{github.ref}}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./GhidraJupyterKotlin/dist/*zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
