name: Main

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: fmagin/setup-ghidra@directLink
        with:
          version: "10.0.1"
          directLink: https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.0.1_build/ghidra_10.0.1_PUBLIC_20210708.zip

      - name: Build with Gradle
        working-directory: ./GhidraJupyterKotlin
        run: gradle buildExtension

      - name: Debug github.ref
        run: echo ${{github.ref}}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./GhidraJupyterKotlin/dist/*zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
